const transactions = [
  {
    id: 1,
    amount: 50000,
    type: "income",
    category: "Salary",
    date: "2025-04-01",
    description: "Monthly salary",
  },
  {
    id: 2,
    amount: 1200,
    type: "expense",
    category: "Food",
    date: "2025-04-02",
    description: "Lunch and snacks",
  },
  {
    id: 3,
    amount: 3000,
    type: "expense",
    category: "Shopping",
    date: "2025-04-03",
    description: "Clothes purchase",
  },
  {
    id: 4,
    amount: 2000,
    type: "expense",
    category: "Transport",
    date: "2025-04-04",
    description: "Fuel and cab",
  },
  {
    id: 5,
    amount: 10000,
    type: "income",
    category: "Freelance",
    date: "2025-04-05",
    description: "Website project",
  },
  {
    id: 6,
    amount: 2500,
    type: "expense",
    category: "Bills",
    date: "2025-04-06",
    description: "Electricity bill",
  },
  {
    id: 7,
    amount: 800,
    type: "expense",
    category: "Food",
    date: "2025-04-07",
    description: "Dinner",
  },
  {
    id: 8,
    amount: 1500,
    type: "expense",
    category: "Entertainment",
    date: "2025-04-08",
    description: "Movie and snacks",
  },
  {
    id: 9,
    amount: 7000,
    type: "income",
    category: "Bonus",
    date: "2025-04-10",
    description: "Performance bonus",
  },
  {
    id: 10,
    amount: 1800,
    type: "expense",
    category: "Shopping",
    date: "2025-04-11",
    description: "Groceries",
  },
];

export default transactions;
